# Generated by Django 5.0.2 on 2024-07-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='gate',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
